compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org/"

npmScopes:
  sethfalco:
    npmRegistryServer: 'https://gitlab.com/api/v4/packages/npm/'
