name: CI

on:
  - 'pull_request'

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with: # TODO: replace SethFalco/svgo:docs -> svg/svgo
          repository: SethFalco/svgo
          ref: docs
          path: .svgo
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run build
